## Covariance And Correlation

In [4]:
import seaborn as sns
import warnings as warn
warn.filterwarnings('ignore')

In [5]:
df=sns.load_dataset('healthexp')
df.head()

   Year        Country  Spending_USD  Life_Expectancy
0  1970        Germany       252.311             70.6
1  1970         France       192.143             72.2
2  1970  Great Britain       123.993             71.9
3  1970          Japan       150.437             72.0
4  1970            USA       326.961             70.9

In [5]:
df = sns.load_dataset('healthexp')
df.head()

   Year        Country  Spending_USD  Life_Expectancy
0  1970        Germany       252.311             70.6
1  1970         France       192.143             72.2
2  1970  Great Britain       123.993             71.9
3  1970          Japan       150.437             72.0
4  1970            USA       326.961             70.9

In [6]:
df.shape

(274, 4)

In [8]:
df.dropna().shape

(274, 4)

In [12]:
df.cov

<bound method DataFrame.cov of      Year        Country  Spending_USD  Life_Expectancy
0    1970        Germany       252.311             70.6
1    1970         France       192.143             72.2
2    1970  Great Britain       123.993             71.9
3    1970          Japan       150.437             72.0
4    1970            USA       326.961             70.9
..    ...            ...           ...              ...
269  2020        Germany      6938.983             81.1
270  2020         France      5468.418             82.3
271  2020  Great Britain      5018.700             80.4
272  2020          Japan      4665.641             84.7
273  2020            USA     11859.179             77.0

[274 rows x 4 columns]>

In [22]:
df1 = df.drop('Country',axis = 1)

In [23]:
##covariance
df1.cov()

                         Year  Spending_USD  Life_Expectancy
Year               201.098848  2.571883e+04        41.915454
Spending_USD     25718.827373  4.817761e+06      4166.800912
Life_Expectancy     41.915454  4.166801e+03        10.733902

In [25]:
df.head()

   Year        Country  Spending_USD  Life_Expectancy
0  1970        Germany       252.311             70.6
1  1970         France       192.143             72.2
2  1970  Great Britain       123.993             71.9
3  1970          Japan       150.437             72.0
4  1970            USA       326.961             70.9

In [24]:
df.head()

   Year        Country  Spending_USD  Life_Expectancy
0  1970        Germany       252.311             70.6
1  1970         France       192.143             72.2
2  1970  Great Britain       123.993             71.9
3  1970          Japan       150.437             72.0
4  1970            USA       326.961             70.9

In [29]:
df1.corr('spearman')

                     Year  Spending_USD  Life_Expectancy
Year             1.000000      0.931598         0.896117
Spending_USD     0.931598      1.000000         0.747407
Life_Expectancy  0.896117      0.747407         1.000000

In [33]:
df1.corr(method='pearson')

                     Year  Spending_USD  Life_Expectancy
Year             1.000000      0.826273         0.902175
Spending_USD     0.826273      1.000000         0.579430
Life_Expectancy  0.902175      0.579430         1.000000

In [36]:
df1.corr(method = 'spearman')

                     Year  Spending_USD  Life_Expectancy
Year             1.000000      0.931598         0.896117
Spending_USD     0.931598      1.000000         0.747407
Life_Expectancy  0.896117      0.747407         1.000000

In [34]:
df1.head()

   Year  Spending_USD  Life_Expectancy
0  1970       252.311             70.6
1  1970       192.143             72.2
2  1970       123.993             71.9
3  1970       150.437             72.0
4  1970       326.961             70.9

In [39]:
# df1 = df.drop('Year', axis = 0)

In [41]:
# df.corr(method = 'spearman')

In [43]:
df.head()

   Year        Country  Spending_USD  Life_Expectancy
0  1970        Germany       252.311             70.6
1  1970         France       192.143             72.2
2  1970  Great Britain       123.993             71.9
3  1970          Japan       150.437             72.0
4  1970            USA       326.961             70.9

In [46]:
df['Country']

0            Germany
1             France
2      Great Britain
3              Japan
4                USA
           ...
269          Germany
270           France
271    Great Britain
272            Japan
273              USA
Name: Country, Length: 274, dtype: object

In [52]:
##spearman rank correlation
df.drop('Country', axis = 1).corr(method='spearman')

                     Year  Spending_USD  Life_Expectancy
Year             1.000000      0.931598         0.896117
Spending_USD     0.931598      1.000000         0.747407
Life_Expectancy  0.896117      0.747407         1.000000

In [9]:
df=sns.load_dataset('flights')
df.head()

   year month  passengers
0  1949   Jan         112
1  1949   Feb         118
2  1949   Mar         132
3  1949   Apr         129
4  1949   May         121

In [49]:
df1.corr()

                     Year  Spending_USD  Life_Expectancy
Year             1.000000      0.826273         0.902175
Spending_USD     0.826273      1.000000         0.579430
Life_Expectancy  0.902175      0.579430         1.000000

In [11]:
df=sns.load_dataset('tips')
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [51]:
# df.corr()

In [53]:
df1.corr()

                     Year  Spending_USD  Life_Expectancy
Year             1.000000      0.826273         0.902175
Spending_USD     0.826273      1.000000         0.579430
Life_Expectancy  0.902175      0.579430         1.000000

In [54]:
df1.corr()

                     Year  Spending_USD  Life_Expectancy
Year             1.000000      0.826273         0.902175
Spending_USD     0.826273      1.000000         0.579430
Life_Expectancy  0.902175      0.579430         1.000000

In [56]:
df1.corr('spearman')

                     Year  Spending_USD  Life_Expectancy
Year             1.000000      0.931598         0.896117
Spending_USD     0.931598      1.000000         0.747407
Life_Expectancy  0.896117      0.747407         1.000000

In [57]:
df1.corr('pearson')

                     Year  Spending_USD  Life_Expectancy
Year             1.000000      0.826273         0.902175
Spending_USD     0.826273      1.000000         0.579430
Life_Expectancy  0.902175      0.579430         1.000000

In [58]:
df1.corr()

                     Year  Spending_USD  Life_Expectancy
Year             1.000000      0.826273         0.902175
Spending_USD     0.826273      1.000000         0.579430
Life_Expectancy  0.902175      0.579430         1.000000

In [6]:
df = sns.load_dataset('tips')
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [8]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [9]:
df[['total_bill', 'tip',  'size']].corr(method = 'spearman')

            total_bill       tip      size
total_bill    1.000000  0.678968  0.604791
tip           0.678968  1.000000  0.468268
size          0.604791  0.468268  1.000000

In [10]:
df[['total_bill', 'tip',  'size']].corr(method = 'pearson')

            total_bill       tip      size
total_bill    1.000000  0.675734  0.598315
tip           0.675734  1.000000  0.489299
size          0.598315  0.489299  1.000000

In [11]:
df[['total_bill', 'tip',  'size']].corr()

            total_bill       tip      size
total_bill    1.000000  0.675734  0.598315
tip           0.675734  1.000000  0.489299
size          0.598315  0.489299  1.000000

In [12]:
df[['total_bill', 'tip',  'size']].corr(method = 'kendall')

            total_bill       tip      size
total_bill    1.000000  0.517181  0.484342
tip           0.517181  1.000000  0.378185
size          0.484342  0.378185  1.000000