## Handling Imbalanced Dataset

1. Up Sampling
2. Down Sampling

In [4]:
import numpy as np, pandas as pd, warnings as warn
warn.filterwarnings('ignore')
from sklearn.utils import resample

In [3]:
import numpy as np
import pandas as pd
# Set the random seed for reproducibility
np.random.seed(123)
# Create a dataframe with two classes
n_samples = 1000
class_0_ratio = 0.9
n_class_0 = int(n_samples * class_0_ratio)
n_class_1 = n_samples - n_class_0

In [34]:
np.random.seed(143)
n_samples = 500
clz_0_ratio = 0.9
n_clz_0 = int(n_samples* clz_0_ratio)
n_clz_1 = n_samples - n_clz_0

In [35]:
n_clz_0,n_clz_1

(450, 50)

In [ ]:
np.random.normal(loc=0, scale=1, size=n_class_0)

In [37]:
clz_0 = pd.DataFrame({'feature-1': np.random.normal(loc = 0, scale = 1, size = n_clz_0),
                      'feature-2': np.random.normal(loc = 0, scale = 1, size = n_clz_0),
                      'target': [ 0 for i in range(n_clz_0)]})

In [38]:
clz_0

     feature-1  feature-2  target
0    -0.833154   0.425295       0
1     1.237691   0.828567       0
2    -2.475731   0.381126       0
3    -1.038631   0.493480       0
4     0.994645  -1.064348       0
..         ...        ...     ...
445   0.292932   0.539658       0
446  -0.247533  -1.089749       0
447   0.996780   0.336265       0
448  -0.521891  -0.033132       0
449  -0.847727   1.426709       0

[450 rows x 3 columns]

In [39]:
clz_1 = pd.DataFrame({'feature-1': np.random.normal(loc = 2, scale = 1, size = n_clz_1),
                      'feature-2': np.random.normal(loc = 2, scale = 1, size = n_clz_1),
                      'target': [ 1 for i in range(n_clz_1)]})

In [42]:
df = pd.concat([clz_0, clz_1])

In [43]:
pd.Categorical(df['target'])

[0, 0, 0, 0, 0, ..., 1, 1, 1, 1, 1]
Length: 500
Categories (2, int64): [0, 1]

In [46]:
df['target'].unique()

array([0, 1])

In [50]:
df['target'].value_counts()

target
0    450
1     50
Name: count, dtype: int64

In [53]:
df_majority = df[df['target'] == 0]
df_minority = df[df['target'] == 1]

In [56]:
df_majority

     feature-1  feature-2  target
0    -0.833154   0.425295       0
1     1.237691   0.828567       0
2    -2.475731   0.381126       0
3    -1.038631   0.493480       0
4     0.994645  -1.064348       0
..         ...        ...     ...
445   0.292932   0.539658       0
446  -0.247533  -1.089749       0
447   0.996780   0.336265       0
448  -0.521891  -0.033132       0
449  -0.847727   1.426709       0

[450 rows x 3 columns]

In [6]:
## CREATE MY DATAFRAME WITH IMBALANCED DATASET
class_0 = pd.DataFrame({
'feature_1': np.random.normal(loc=0, scale=1, size=n_clAass_0),
    'feature_2': np.random.normal(loc=0, scale=1, size=n_class_0),
    'target': [0] * n_class_0
})

class_1 = pd.DataFrame({
    'feature_1': np.random.normal(loc=2, scale=1, size=n_class_1),
    'feature_2': np.random.normal(loc=2, scale=1, size=n_class_1),
    'target': [1] * n_class_1
})

In [7]:
df=pd.concat([class_0,class_1]).reset_index(drop=True)

In [8]:
df.tail()

     feature_1  feature_2  target
995   1.376371   2.845701       1
996   2.239810   0.880077       1
997   1.131760   1.640703       1
998   2.902006   0.390305       1
999   2.697490   2.013570       1

In [9]:
df['target'].value_counts()

target
0    900
1    100
Name: count, dtype: int64

In [10]:
## upsampling
df_minority=df[df['target']==1]
df_majority=df[df['target']==0]

In [11]:
from sklearn.utils import resample
df_minority_upsampled=resample(df_minority,replace=True, #Sample With replacement
         n_samples=len(df_majority),
         random_state=42
        )

In [12]:
df_minority_upsampled.shape

(900, 3)

In [13]:
df_minority_upsampled.head()

     feature_1  feature_2  target
951   1.125854   1.843917       1
992   2.196570   1.397425       1
914   1.932170   2.998053       1
971   2.272825   3.034197       1
960   2.870056   1.550485       1

In [14]:
df_upsampled=pd.concat([df_majority,df_minority_upsampled])

In [15]:
df_upsampled['target'].value_counts()

target
0    900
1    900
Name: count, dtype: int64

## Down Sampling

In [5]:
clz_0 = pd.DataFrame({'data1': np.random.normal(loc = 0, scale = 1, size = 400), 
                      'data2': np.random.normal(loc=0, scale = 1, size=400), 'target': [0]*400})
clz_1 = pd.DataFrame({'data1': np.random.normal(loc = 0, scale = 1, size = 100), 
                      'data2': np.random.normal(loc=0, scale = 1, size=100), 'target': [1]*100})
df1 = pd.concat([clz_0, clz_1], ignore_index = 0)

In [7]:
df1['target'].value_counts()

target
0    400
1    100
Name: count, dtype: int64

In [9]:
df1_minor = df1[df1['target'] == 1]
df1_major = df1[df1['target'] == 0]
df1_minor_upsampled = resample(df1_minor, n_samples = len(df1_major), random_state = 42)
balanced_df1 = pd.concat([df1_major, df1_minor_upsampled], ignore_index = True)

In [10]:
balanced_df1['target'].value_counts()

target
0    400
1    400
Name: count, dtype: int64

In [18]:
df1_major_downsampled = resample(df1_major, n_samples = len(df1_minor), replace = False, random_state = 42)
balanced_df1 = pd.concat([df1_minor, df1_major_downsampled], ignore_index = True)

In [19]:
balanced_df1['target'].value_counts()

target
1    100
0    100
Name: count, dtype: int64

In [20]:
balanced_df1.duplicated().sum()

0

In [24]:
df1_major_downsampled = resample(df1_major, n_samples = len(df1_minor), replace = True, random_state = 42)
balanced_df1 = pd.concat([df1_minor, df1_major_downsampled], ignore_index = True)

In [25]:
balanced_df1.duplicated().sum()

14

In [16]:
import pandas as pd

# Set the random seed for reproducibility
np.random.seed(123)
()
# Create a dataframe with two classes
n_samples = 1000
class_0_ratio = 0.9
n_class_0 = int(n_samples * class_0_ratio)
n_class_1 = n_samples - n_class_0

class_0 = pd.DataFrame({
    'feature_1': np.random.normal(loc=0, scale=1, size=n_class_0),
    'feature_2': np.random.normal(loc=0, scale=1, size=n_class_0),
    'target': [0] * n_class_0
})

class_1 = pd.DataFrame({
    'feature_1': np.random.normal(loc=2, scale=1, size=n_class_1),
    'feature_2': np.random.normal(loc=2, scale=1, size=n_class_1),
    'target': [1] * n_class_1
})

df = pd.concat([class_0, class_1]).reset_index(drop=True)

# Check the class distribution
print(df['target'].value_counts())

target
0    900
1    100
Name: count, dtype: int64

In [17]:
## downsampling
df_minority=df[df['target']==1]
df_majority=df[df['target']==0]

In [18]:
from sklearn.utils import resample
df_majority_downsampled=resample(df_majority,replace=False, #Sample With replacement
         n_samples=len(df_minority),
         random_state=42
        )

In [19]:
df_majority_downsampled.shape

(100, 3)

In [20]:
df_downsampled=pd.concat([df_minority,df_majority_downsampled])

In [21]:
df_downsampled['target'].value_counts()

target
1    100
0    100
Name: count, dtype: int64